#!/usr/bin/env bash
# plugins/hoardinator/scripts/upload-sessions.sh
# Uploads SQL batch files (generated by parse-sessions.py) to Supabase
# via the Management API: POST /v1/projects/{ref}/database/query
#
# Usage:
#   upload-sessions.sh [options]
#
# Options:
#   --input <dir>        Directory containing SQL batch files (default: /tmp/hoardinator-sql/)
#   --project <ref>      Override SUPABASE_PROJECT_REF
#   --dry-run            Show what would be uploaded without executing
#   --verbose            Show detailed output

set -euo pipefail

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
INPUT_DIR="/tmp/hoardinator-sql/"
PROJECT_REF="${SUPABASE_PROJECT_REF:-}"
DRY_RUN=false
VERBOSE=false

SUPABASE_API="https://api.supabase.com/v1/projects"

# Temp file list for cleanup
TEMP_FILES=()

# ---------------------------------------------------------------------------
# Cleanup trap — remove temp files on exit (normal or error)
# ---------------------------------------------------------------------------
cleanup() {
    for f in "${TEMP_FILES[@]:-}"; do
        [ -f "$f" ] && rm -f "$f"
    done
}
trap cleanup EXIT INT TERM

# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------
info()    { echo -e "${CYAN}[info]${RESET}  $*"; }
success() { echo -e "${GREEN}[ok]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET}  $*"; }
error()   { echo -e "${RED}[err]${RESET}   $*" >&2; }
verbose() { $VERBOSE && echo -e "${BOLD}[debug]${RESET} $*" || true; }

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------
usage() {
    cat <<'USAGE'
upload-sessions.sh — Upload SQL batch files to Supabase Management API

Usage:
  upload-sessions.sh [options]

Options:
  --input <dir>        Directory containing SQL batch files
                       (default: /tmp/hoardinator-sql/)
  --project <ref>      Override SUPABASE_PROJECT_REF env var
  --dry-run            Show what would be uploaded without executing
  --verbose            Show detailed output
  -h, --help           Show this help message

Environment variables:
  SUPABASE_ACCESS_TOKEN   Personal access token for Supabase Management API (required)
  SUPABASE_PROJECT_REF    Project reference ID (can be overridden with --project)
USAGE
}

# ---------------------------------------------------------------------------
# Parse CLI arguments
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --input)
            INPUT_DIR="$2"
            shift 2
            ;;
        --project)
            PROJECT_REF="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Validate environment & inputs
# ---------------------------------------------------------------------------

# Access token — required (never echo it)
if [ -z "${SUPABASE_ACCESS_TOKEN:-}" ]; then
    error "SUPABASE_ACCESS_TOKEN is not set."
    error "Get one at https://supabase.com/dashboard/account/tokens"
    exit 1
fi

# Project ref — required
if [ -z "$PROJECT_REF" ]; then
    error "SUPABASE_PROJECT_REF is not set and --project was not provided."
    exit 1
fi

# Project ref format — alphanumeric only (Supabase refs are lowercase alnum, ~20 chars)
if [[ ! "$PROJECT_REF" =~ ^[a-zA-Z0-9]+$ ]]; then
    error "Invalid PROJECT_REF format: must be alphanumeric only."
    exit 1
fi

# Input directory must exist
if [ ! -d "$INPUT_DIR" ]; then
    error "Input directory does not exist: $INPUT_DIR"
    exit 1
fi

# ---------------------------------------------------------------------------
# Discover batch files
# ---------------------------------------------------------------------------
# Sort numerically by the number in batch_NNN.sql
BATCH_FILES=()
while IFS= read -r line; do
    BATCH_FILES+=("$line")
done < <(
    find "$INPUT_DIR" -maxdepth 1 -name 'batch_*.sql' -type f \
    | sort -t_ -k2 -n
)

if [ ${#BATCH_FILES[@]} -eq 0 ]; then
    warn "No batch_*.sql files found in $INPUT_DIR"
    exit 0
fi

TOTAL=${#BATCH_FILES[@]}
info "Found ${BOLD}${TOTAL}${RESET} batch file(s) in ${INPUT_DIR}"
verbose "Project ref: $PROJECT_REF"
verbose "API endpoint: ${SUPABASE_API}/${PROJECT_REF}/database/query"

if $DRY_RUN; then
    warn "DRY RUN — no requests will be sent"
fi

echo ""

# ---------------------------------------------------------------------------
# Upload loop
# ---------------------------------------------------------------------------
SUCCEEDED=0
FAILED=0
FAILED_FILES=()

for i in "${!BATCH_FILES[@]}"; do
    batch_file="${BATCH_FILES[$i]}"
    batch_name=$(basename "$batch_file")
    seq=$(( i + 1 ))

    printf "${BOLD}[%d/%d]${RESET} Uploading %s... " "$seq" "$TOTAL" "$batch_name"

    # Read SQL content
    sql_content=$(<"$batch_file")

    if [ -z "$sql_content" ]; then
        warn "SKIP (empty file)"
        continue
    fi

    verbose "SQL size: ${#sql_content} bytes"

    # Build JSON payload via jq to safely escape the SQL string
    tmp_json=$(mktemp /tmp/upload-batch-XXXXXX).json
    TEMP_FILES+=("$tmp_json")

    if ! jq -n --arg query "$sql_content" '{"query": $query}' > "$tmp_json" 2>/dev/null; then
        echo -e "${RED}FAIL${RESET} (JSON encoding error)"
        error "  Could not encode SQL to JSON for $batch_name"
        FAILED=$(( FAILED + 1 ))
        FAILED_FILES+=("$batch_name")
        continue
    fi

    verbose "JSON payload: $(wc -c < "$tmp_json") bytes -> $tmp_json"

    # Dry-run: skip the actual request
    if $DRY_RUN; then
        echo -e "${YELLOW}DRY-RUN${RESET}"
        SUCCEEDED=$(( SUCCEEDED + 1 ))
        continue
    fi

    # POST to Supabase Management API
    # Capture both HTTP status and response body
    http_status=""
    response_body=""

    # Use a temp file for the response body so we can get the status code separately
    tmp_resp=$(mktemp /tmp/upload-resp-XXXXXX).json
    TEMP_FILES+=("$tmp_resp")

    # Disable set -e for this curl call so we can handle errors ourselves
    set +e
    http_status=$(curl -s -o "$tmp_resp" -w "%{http_code}" \
        -X POST \
        "${SUPABASE_API}/${PROJECT_REF}/database/query" \
        -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" \
        -H "Content-Type: application/json" \
        -d @"$tmp_json" \
        --max-time 120)
    curl_exit=$?
    set -e

    # Evaluate result
    if [ $curl_exit -ne 0 ]; then
        echo -e "${RED}FAIL${RESET} (curl error, exit code $curl_exit)"
        error "  curl failed for $batch_name (exit $curl_exit)"
        FAILED=$(( FAILED + 1 ))
        FAILED_FILES+=("$batch_name")
    elif [[ "$http_status" == "200" || "$http_status" == "201" ]]; then
        echo -e "${GREEN}OK${RESET} (HTTP $http_status)"
        SUCCEEDED=$(( SUCCEEDED + 1 ))
        if $VERBOSE && [ -f "$tmp_resp" ]; then
            response_body=$(<"$tmp_resp")
            verbose "Response: ${response_body:0:200}"
        fi
    else
        echo -e "${RED}FAIL${RESET} (HTTP $http_status)"
        error "  $batch_name returned HTTP $http_status"
        if [ -f "$tmp_resp" ]; then
            response_body=$(<"$tmp_resp")
            # Show first 300 chars of error response
            error "  Response: ${response_body:0:300}"
        fi
        FAILED=$(( FAILED + 1 ))
        FAILED_FILES+=("$batch_name")
    fi
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}========================================${RESET}"
echo -e "${BOLD} Upload Summary${RESET}"
echo -e "${BOLD}========================================${RESET}"
echo -e " Total batches:  ${TOTAL}"
echo -e " ${GREEN}Succeeded:${RESET}       ${SUCCEEDED}"
echo -e " ${RED}Failed:${RESET}          ${FAILED}"

if [ ${#FAILED_FILES[@]} -gt 0 ]; then
    echo ""
    echo -e " ${RED}Failed files:${RESET}"
    for f in "${FAILED_FILES[@]}"; do
        echo -e "   - $f"
    done
fi

echo -e "${BOLD}========================================${RESET}"

# Display summary.json if it exists in the input directory
SUMMARY_FILE="${INPUT_DIR%/}/summary.json"
if [ -f "$SUMMARY_FILE" ]; then
    echo ""
    echo -e "${CYAN}Parse summary (summary.json):${RESET}"
    if command -v jq &>/dev/null; then
        jq '.' "$SUMMARY_FILE"
    else
        cat "$SUMMARY_FILE"
    fi
fi

# Exit with appropriate code
if [ "$FAILED" -gt 0 ]; then
    exit 1
fi

exit 0
