#!/bin/bash
# plugins/architect/scripts/upload-sessions.sh
# Upload Session Hoardinator SQL batches to Supabase via the Management API.
#
# Prerequisites:
#   - Supabase plugin installed in Claude Code
#   - SUPABASE_URL   — e.g. https://hdhmwaldvzxwhimoemap.supabase.co
#   - SUPABASE_SERVICE_ROLE_KEY — service role key (Supabase → Settings → API)
#
# Usage:
#   bash upload-sessions.sh <sql-dir>
#
# The script derives the Supabase project ref from SUPABASE_URL and uploads
# each .sql file in <sql-dir> to the Management API database query endpoint.

set -euo pipefail

SQL_DIR="${1:-}"

if [ -z "$SQL_DIR" ]; then
  echo "Usage: upload-sessions.sh <sql-dir>"
  echo ""
  echo "  <sql-dir>  Directory containing .sql files generated by parse-sessions.py"
  echo ""
  echo "Required environment variables:"
  echo "  SUPABASE_URL             https://<project-ref>.supabase.co"
  echo "  SUPABASE_SERVICE_ROLE_KEY  service role key from Supabase Settings > API"
  exit 1
fi

# ── Prerequisite checks ───────────────────────────────────────────────────────

MISSING=0

if [ -z "${SUPABASE_URL:-}" ]; then
  echo "✗ SUPABASE_URL is not set"
  echo "  Set it to your Supabase project URL:"
  echo "  export SUPABASE_URL=https://hdhmwaldvzxwhimoemap.supabase.co"
  MISSING=1
fi

if [ -z "${SUPABASE_SERVICE_ROLE_KEY:-}" ]; then
  echo "✗ SUPABASE_SERVICE_ROLE_KEY is not set"
  echo "  Find it in your Supabase project: Settings > API > service_role key"
  echo "  export SUPABASE_SERVICE_ROLE_KEY=<your-key>"
  MISSING=1
fi

if [ "$MISSING" -eq 1 ]; then
  echo ""
  echo "Session Hoardinator requires the Supabase plugin to be installed and"
  echo "Supabase API credentials to be set as environment variables."
  echo "See plugins/architect/skills/ingest/SKILL.md for setup instructions."
  exit 1
fi

if ! command -v curl &>/dev/null; then
  echo "✗ curl is required but not installed"
  exit 1
fi

if ! command -v python3 &>/dev/null; then
  echo "✗ python3 is required but not installed"
  exit 1
fi

# ── Validate SQL directory ────────────────────────────────────────────────────

if [ ! -d "$SQL_DIR" ]; then
  echo "✗ SQL directory not found: $SQL_DIR"
  echo "  Run parse-sessions.py first to generate SQL files."
  exit 1
fi

mapfile -t SQL_FILES < <(find "$SQL_DIR" -maxdepth 1 -name "*.sql" | sort)

if [ "${#SQL_FILES[@]}" -eq 0 ]; then
  echo "No .sql files found in $SQL_DIR"
  exit 0
fi

# ── Derive Supabase project ref ───────────────────────────────────────────────

PROJECT_REF=$(echo "$SUPABASE_URL" | sed 's|https://||;s|\.supabase\.co.*||')

if [ -z "$PROJECT_REF" ]; then
  echo "✗ Could not derive project ref from SUPABASE_URL: $SUPABASE_URL"
  echo "  Expected format: https://<project-ref>.supabase.co"
  exit 1
fi

API_URL="https://api.supabase.com/v1/projects/${PROJECT_REF}/database/query"

echo "Session Hoardinator upload:"
echo "  Project ref  : $PROJECT_REF"
echo "  SQL files    : ${#SQL_FILES[@]}"
echo "  Directory    : $SQL_DIR"
echo ""

# ── Upload loop ───────────────────────────────────────────────────────────────

SUCCESS=0
FAILURE=0

TEMP_JSON=$(mktemp /tmp/hoardinator-XXXXXX.json)
trap 'rm -f "$TEMP_JSON"' EXIT

for sql_file in "${SQL_FILES[@]}"; do
  filename=$(basename "$sql_file")

  # Build JSON payload via Python to handle arbitrary SQL content safely
  python3 - "$sql_file" > "$TEMP_JSON" <<'PYEOF'
import json, sys
sql = open(sys.argv[1], encoding="utf-8").read()
print(json.dumps({"query": sql}))
PYEOF

  response=$(
    curl -sS -w "\n%{http_code}" \
      -X POST "$API_URL" \
      -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
      -H "Content-Type: application/json" \
      --data-binary @"$TEMP_JSON" \
      2>&1
  )

  http_code=$(echo "$response" | tail -n1)
  body=$(echo "$response" | head -n-1)

  if [[ "$http_code" =~ ^2 ]]; then
    echo "  ✓ $filename"
    SUCCESS=$((SUCCESS + 1))
  else
    echo "  ✗ $filename  (HTTP $http_code)"
    echo "    $(echo "$body" | head -c 300)"
    FAILURE=$((FAILURE + 1))
  fi
done

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "Upload complete:"
echo "  ✓ Succeeded : $SUCCESS"
echo "  ✗ Failed    : $FAILURE"

if [ "$FAILURE" -gt 0 ]; then
  echo ""
  echo "Some uploads failed. Common causes:"
  echo "  - SUPABASE_SERVICE_ROLE_KEY has insufficient permissions"
  echo "  - Tables (sessions, messages, tool_calls) do not exist yet"
  echo "  - Network connectivity issue"
  exit 1
fi
